[package]
name = "smart-compass-v1"
version = "0.1.0"
authors = ["Bryan Stitt <bryan@stitthappens.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
accelerometer = "0.12"
blake2 = { version = "0.9", default-features = false }
embedded-sdmmc = "0.3"
feather_m0 = { path = "../atsamd/boards/feather_m0", features = ["unproven"] }
# TODO: this needs updates to match the latest dependencies on feather_m0
radio-sx127x = { path = "../rust-radio-sx127x", default-features = false }
smart-leds = "0.3"
# make sure ws2812 crate uses the same smart-leds-trait crate as smart-leds
ws2812-nop-samd21 = "0.3"
shared-bus = { path = "../shared-bus", features = ["cortexm"] }

# TODO: these require std
# adafruit_gps = "0.3"
# make sure adafruit-gps crate uses the same serialport crate as this
# serialport = { version = "3.3.0", default-features = false }

# TODO: use these from feather_m0
cortex-m = "*"
cortex-m-rt = "*"
cortex-m-semihosting = "0.3.5"
panic-halt = "*"

# TODO: use these from radio-sx127x
embedded-hal = { version = "0.2.4", features = ["unproven"] }
embedded-spi = { version = "0.6.2", default-features = false }
