[package]
name = "smart-compass-v1"
version = "0.1.0"
authors = ["Bryan Stitt <bryan@stitthappens.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# cortex-m = "*"
# cortex-m-semihosting = "*"
feather_m0 = { version = "*", features = ["panic_semihosting"] }
# panic_halt = "*"
# panic_semihosting = "*"
