[package]
name = "smart-compass-v1"
version = "0.1.0"
authors = ["Bryan Stitt <bryan@stitthappens.com>"]
edition = "2018"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
asm-delay = "0.9"
blake2 = { version = "0.9", default-features = false }
cortex-m-rtic = "0.5"
cortex-m-semihosting = "0.3.3"
embedded-sdmmc = "0.3"
heapless = "0.5"
numtoa = "*"
panic-semihosting = "0.5"
radio-sx127x = { path = "../rust-radio-sx127x", default-features = false }
shared-bus-rtic = "0.2.2"
smart-leds = "0.3"
yanp = "0.1.1"
# make sure ws2812 crate uses the same smart-leds-trait crate as smart-leds
# TODO: is this crate compatible? do we need one for a stm32f3?
ws2812-spi = "*"

# TODO: these require std
# adafruit_gps = "0.3"
# make sure adafruit-gps crate uses the same serialport crate as this
# serialport = { version = "3.3.0", default-features = false }

# TODO: use these from radio-sx127x
embedded-hal = { version = "0.2.4", features = ["unproven"] }
embedded-spi = { version = "0.6.2", default-features = false }

[dependencies.stm32f3-discovery]
path = "../stm32f3-discovery"

# this lets you use `cargo fix`!
[[bin]]
name = "smart-compass-v1"
test = false
bench = false

[profile.release]
codegen-units = 1 # better optimizations
debug = true # symbols are nice and they don't increase the size on Flash
lto = true # better optimizations
